### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by collinx** [ccann/gregor#6]
@ccann can you please specify the license for Gregor? Is it same as given on [clojar](https://clojars.org/io.weft/gregor/)?

**Comment by ccann** [comment]
Hi, the license is specified in `project.clj`:
https://github.com/ccann/gregor/blob/8f9ec0c98f118a1d6a5e4759ef80d4c2064166ca/project.clj#L5

I added it to the readme and added a copy of the license as well.

**Comment by collinx** [comment]
Oh! I missed that. Thanks for adding License to the repository. 👍
